Repository magiclabs/magic-js, pull requests merged in 2021-09, with the labels that each got.

#200 bypass webcrypto on non web platforms
  packages/@magic-sdk/provider/src/core/payload-transport.ts
  packages/@magic-sdk/provider/test/spec/core/payload-transport/post.spec.ts
Labels: minor

#201 [Feat]: Update type signature of `RpcProviderModule` to implement Web3's `AbstractProvider`
  packages/@magic-sdk/provider/package.json
  packages/@magic-sdk/provider/src/core/sdk.ts
  packages/@magic-sdk/provider/src/modules/rpc-provider.ts
  yarn.lock
Labels: minor

#205 Update next branch
  packages/@magic-sdk/react-native/src/index.ts
  packages/magic-sdk/src/index.ts
Labels: major

#209 Fix SemVer cyclic dependency issues with some hacks
  .eslintignore
  package.json
  packages/@magic-sdk/provider/babel.config.json
  packages/@magic-sdk/provider/jest.config.ts
  packages/@magic-sdk/provider/package.json
  packages/@magic-sdk/provider/src/core/sdk.ts
  packages/@magic-sdk/provider/src/util/index.ts
  packages/@magic-sdk/provider/src/util/semver.js
  packages/@magic-sdk/provider/src/util/semver.ts
  packages/@magic-sdk/react-native/babel.config.js
  packages/@magic-sdk/react-native/babel.config.json
  packages/@magic-sdk/react-native/package.json
  packages/magic-sdk/babel.config.json
  yarn.lock
Labels: patch

#210 Import regeneratorRuntime in Magic JS (non-CDN version)
  packages/@magic-sdk/commons/package.json
  packages/@magic-sdk/provider/package.json
  packages/@magic-sdk/react-native/package.json
  packages/@magic-sdk/types/package.json
  packages/magic-sdk/src/index.ts
  yarn.lock
Labels: patch

#212 Enable `skipLibCheck: false` to work with Magic SDK + TypeScript projects
  packages/@magic-sdk/provider/package.json
  packages/magic-sdk/package.json
  scripts/bin/build.ts
  scripts/bin/wsrun/build-package.ts
  yarn.lock
Labels: patch

#214 Fix CJS-dependent entry-points using the 'exports' field in package.json
  CONTRIBUTING.md
  package.json
  packages/@magic-sdk/commons/package.json
  packages/@magic-sdk/provider/package.json
  packages/@magic-sdk/types/package.json
  packages/magic-sdk/package.json
  scripts/bin/wsrun/build-package.ts
  scripts/utils/microbundle.ts
  yarn.lock
Labels: patch

#215 Fix `regeneratorRuntime` is not defined in `@magic-sdk/provider`
  packages/@magic-sdk/provider/src/index.cjs.ts
  packages/@magic-sdk/provider/src/index.es.ts
  packages/magic-sdk/src/index.cjs.ts
  packages/magic-sdk/src/index.es.ts
  packages/magic-sdk/src/index.ts
  scripts/bin/wsrun/build-package.ts
  scripts/utils/microbundle.ts
  yarn.lock
Labels: patch

#217 Add `@magic-sdk/pnp` package for out-of-the-box login page UIs
  CONTRIBUTING.md
  package.json
  packages/@magic-sdk/commons/src/index.ts
  packages/@magic-sdk/commons/tsconfig.json
  packages/@magic-sdk/pnp/.eslintignore
  packages/@magic-sdk/pnp/.eslintrc.js
  packages/@magic-sdk/pnp/.lintstagedrc.yml
  packages/@magic-sdk/pnp/.prettierrc.js
  packages/@magic-sdk/pnp/CHANGELOG.md
  packages/@magic-sdk/pnp/LICENSE
  packages/@magic-sdk/pnp/README.md
  packages/@magic-sdk/pnp/babel.config.json
  packages/@magic-sdk/pnp/jest.config.ts
  packages/@magic-sdk/pnp/package.json
  packages/@magic-sdk/pnp/src/index.ts
  packages/@magic-sdk/pnp/src/login.ts
  packages/@magic-sdk/pnp/src/pnp-extension.ts
  packages/@magic-sdk/pnp/src/types.ts
  packages/@magic-sdk/pnp/src/utils.ts
  packages/@magic-sdk/pnp/tsconfig.json
  packages/@magic-sdk/provider/src/core/sdk.ts
  packages/@magic-sdk/provider/src/index.ts
  packages/@magic-sdk/provider/src/modules/base-extension.ts
  packages/@magic-sdk/provider/test/spec/util/storage.spec.ts
  packages/@magic-sdk/provider/test/tsconfig.json
  packages/@magic-sdk/provider/tsconfig.json
  packages/@magic-sdk/react-native/src/index.ts
  packages/@magic-sdk/react-native/test/tsconfig.json
  packages/@magic-sdk/react-native/tsconfig.json
  packages/@magic-sdk/types/tsconfig.json
  packages/magic-sdk/package.json
  packages/magic-sdk/src/index.cdn.ts
  packages/magic-sdk/src/index.ts
  packages/magic-sdk/test/tsconfig.json
  packages/magic-sdk/tsconfig.json
  scripts/bin/clean.ts
  scripts/bin/wsrun/build-package.ts
  scripts/bin/wsrun/test:unit.ts
  scripts/tsconfig.json
  scripts/utils/microbundle.ts
  scripts/utils/workspace-helpers.ts
  tsconfig.json
  tsconfig.settings.json
  tsconfig.settings.test.json
  yarn.lock
Labels: skip-release

#219 Change 'externals' and 'global' condition in magic-sdk > CDN build
  packages/magic-sdk/package.json
  scripts/bin/wsrun/build-package.ts
  yarn.lock
Labels: patch
