Repository magiclabs/magic-js, pull requests merged in 2021-01, with the labels that each got.

#157 Improve i18n Support
  packages/provider/src/core/sdk.ts
Labels: minor, skip-release

#158 Iframe accessibility improvements: Add `title` attribute and auto-focus when UI is showing
  packages/commons/package.json
  packages/web/src/iframe-controller.ts
  packages/web/test/spec/iframe-controller/hideOverlay.spec.ts
  packages/web/test/spec/iframe-controller/init.spec.ts
  packages/web/test/spec/iframe-controller/showOverlay.spec.ts
Labels: minor

#160 Support UTF-8 characters when encoding iframe options to Base64
  packages/provider/src/util/base64-json.ts
Labels: patch
