Repository magiclabs/magic-js, pull requests merged in 2021-11, with the labels that each got.

#237 Remove 'semver' re-export from '@magic-sdk/provider' utils
  packages/@magic-sdk/provider/src/util/index.ts
Labels: patch, skip-release

#240 Add parameters for ToS and privacy links to `@magic-sdk/pnp`
  packages/@magic-sdk/pnp/src/context/login.ts
  packages/@magic-sdk/pnp/src/pnp-extension.ts
  packages/@magic-sdk/pnp/src/utils/script-data.ts
  yarn.lock
Labels: minor

#242 move crypto-js to devDependencies to fix bundling error
  packages/@magic-ext/oauth/package.json
Labels: patch
