Repository magiclabs/magic-js, pull requests merged in 2021-08, with the labels that each got.

#193 register access control rpc error code
  packages/types/src/core/exception-types.ts
Labels: patch

#195 Update `auto`
  package.json
  yarn.lock
Labels: skip-release, dependencies

#199 Custom session duration
  packages/@magic-sdk/provider/package.json
  packages/@magic-sdk/provider/src/core/payload-transport.ts
  packages/@magic-sdk/provider/src/modules/auth.ts
  packages/@magic-sdk/provider/src/modules/base-module.ts
  packages/@magic-sdk/provider/src/modules/user.ts
  packages/@magic-sdk/provider/src/util/uuid.ts
  packages/@magic-sdk/provider/src/util/web-crypto.ts
  packages/@magic-sdk/provider/test/setup.ts
  packages/@magic-sdk/provider/test/spec/core/payload-transport/post.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/auth/loginWithCredential.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/auth/loginWithMagicLink.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/user/generateIdToken.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/user/getIdToken.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/user/getMetadata.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/user/isLoggedIn.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/user/logout.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/user/updateEmail.spec.ts
  packages/@magic-sdk/provider/test/spec/util/web-crypto.spec.ts
  packages/@magic-sdk/types/src/core/message-types.ts
  yarn.lock
Labels: major
