Repository magiclabs/magic-js, pull requests merged in 2022-01, with the labels that each got.

#263 magic-conflux extension
  packages/@magic-ext/conflux/.eslintignore
  packages/@magic-ext/conflux/.eslintrc.js
  packages/@magic-ext/conflux/.lintstagedrc.yml
  packages/@magic-ext/conflux/.prettierrc.js
  packages/@magic-ext/conflux/CHANGELOG.md
  packages/@magic-ext/conflux/LICENSE
  packages/@magic-ext/conflux/package.json
  packages/@magic-ext/conflux/src/index.cdn.ts
  packages/@magic-ext/conflux/src/index.native.ts
  packages/@magic-ext/conflux/src/index.ts
  packages/@magic-ext/conflux/src/types.ts
  packages/@magic-ext/conflux/tsconfig.json
  yarn.lock
Labels: patch, skip-release

#267 Update CI to build forked branches without ENV vars
  .circleci/config.yml
Labels: skip-release, internal

#270 Fix CDN build targets
  .eslintrc.js
  package.json
  packages/@magic-ext/algorand/src/index.cdn.ts
  packages/@magic-ext/avalanche/src/index.cdn.ts
  packages/@magic-ext/bitcoin/src/index.cdn.ts
  packages/@magic-ext/cosmos/src/index.cdn.ts
  packages/@magic-ext/flow/src/index.cdn.ts
  packages/@magic-ext/harmony/src/index.cdn.ts
  packages/@magic-ext/icon/src/index.cdn.ts
  packages/@magic-ext/near/src/index.cdn.ts
  packages/@magic-ext/oauth/src/index.cdn.ts
  packages/@magic-ext/polkadot/src/index.cdn.ts
  packages/@magic-ext/solana/src/index.cdn.ts
  packages/@magic-ext/tezos/src/index.cdn.ts
  packages/@magic-ext/webauthn/src/index.cdn.ts
  packages/@magic-ext/zilliqa/src/index.cdn.ts
  packages/magic-sdk/src/index.cdn.ts
  scripts/bin/scaffold/template/hybrid/src/index.cdn.ts
  scripts/bin/scaffold/template/web/src/index.cdn.ts
  scripts/utils/esbuild.ts
  yarn.lock
Labels: patch

#271 Add 'dev' script
  CONTRIBUTING.md
  package.json
  scripts/bin/build.ts
  scripts/bin/dev.ts
  scripts/bin/wsrun/build-package.ts
  scripts/utils/environment.ts
  scripts/utils/esbuild.ts
  scripts/utils/workspace-helpers.ts
  yarn.lock
Labels: skip-release, internal

#275 Add special parsing logic to handle typed array in payload
  packages/@magic-sdk/react-native/src/react-native-webview-controller.tsx
  packages/@magic-sdk/react-native/test/spec/react-native-webview-controller/handleReactNativeWebViewMessage.spec.ts
Labels: minor
