Repository magiclabs/magic-js, pull requests merged in 2022-07, with the labels that each got.

#335 Enable bundle Id in Expo
  packages/@magic-sdk/provider/src/core/sdk-environment.ts
  packages/@magic-sdk/provider/src/core/sdk.ts
  packages/@magic-sdk/provider/test/spec/core/sdk/constructor.spec.ts
  packages/@magic-sdk/react-native/jest.config.ts
  packages/@magic-sdk/react-native/package.json
  packages/@magic-sdk/react-native/src/index.ts
  packages/@magic-sdk/types/src/core/query-types.ts
  yarn.lock
Labels: major

#336 add signMessage for solana extension
  packages/@magic-ext/solana/src/index.ts
  packages/@magic-ext/solana/src/type.ts
Labels: minor

#338 Revert "Revert "Enable bundle Id in Expo""
  packages/@magic-sdk/provider/src/core/sdk-environment.ts
  packages/@magic-sdk/provider/src/core/sdk.ts
  packages/@magic-sdk/provider/test/spec/core/sdk/constructor.spec.ts
  packages/@magic-sdk/react-native/jest.config.ts
  packages/@magic-sdk/react-native/package.json
  packages/@magic-sdk/react-native/src/index.ts
  packages/@magic-sdk/types/src/core/query-types.ts
  yarn.lock
Labels: major

#339 Update Readme and manual version bump for releases
  packages/@magic-sdk/provider/package.json
  packages/@magic-sdk/react-native/README.md
  packages/@magic-sdk/react-native/package.json
  packages/@magic-sdk/types/package.json
  yarn.lock
Labels: skip-release
