Repository magiclabs/magic-js, pull requests merged in 2022-09, with the labels that each got.

#357 Add RN TypedArray stringify conversion logic
  packages/@magic-sdk/react-native/src/react-native-webview-controller.tsx
  packages/@magic-sdk/react-native/test/spec/react-native-webview-controller/_post.spec.ts
Labels: patch

#362 Harryxue sc 61854 m2 magic sdk support goerli testnet and release
  packages/@magic-sdk/types/src/modules/rpc-provider-types.ts
Labels: minor

#364 drop legacy testnet support
  packages/@magic-sdk/types/src/modules/rpc-provider-types.ts
  yarn.lock
Labels: major
