Repository magiclabs/magic-js, pull requests merged in 2022-08, with the labels that each got.

#316 initial commit for Connect Extenstion
  packages/@magic-ext/connect/.eslintignore
  packages/@magic-ext/connect/.eslintrc.js
  packages/@magic-ext/connect/.lintstagedrc.yml
  packages/@magic-ext/connect/.prettierrc.js
  packages/@magic-ext/connect/CHANGELOG.md
  packages/@magic-ext/connect/LICENSE
  packages/@magic-ext/connect/README.md
  packages/@magic-ext/connect/package.json
  packages/@magic-ext/connect/src/index.cdn.ts
  packages/@magic-ext/connect/src/index.ts
  packages/@magic-ext/connect/src/types.ts
  packages/@magic-ext/connect/tsconfig.json
  yarn.lock
Labels: major, prerelease

#345 bump web-expo-browser version
  packages/@magic-ext/react-native-oauth/package.json
  packages/@magic-ext/react-native-oauth/src/index.ts
  yarn.lock
Labels: minor

#346 add @magic-ext/ed25519
  packages/@magic-ext/ed25519/.eslintignore
  packages/@magic-ext/ed25519/.eslintrc.js
  packages/@magic-ext/ed25519/.lintstagedrc.yml
  packages/@magic-ext/ed25519/.prettierrc.js
  packages/@magic-ext/ed25519/CHANGELOG.md
  packages/@magic-ext/ed25519/LICENSE
  packages/@magic-ext/ed25519/package.json
  packages/@magic-ext/ed25519/src/index.cdn.ts
  packages/@magic-ext/ed25519/src/index.native.ts
  packages/@magic-ext/ed25519/src/index.ts
  packages/@magic-ext/ed25519/src/types.ts
  packages/@magic-ext/ed25519/tsconfig.json
  yarn.lock
Labels: patch
