Repository magiclabs/magic-js, pull requests merged in 2023-08, with the labels that each got.

#597 [82686] revive hedera extension
  packages/@magic-ext/hedera/.eslintignore
  packages/@magic-ext/hedera/.eslintrc.js
  packages/@magic-ext/hedera/.lintstagedrc.yml
  packages/@magic-ext/hedera/.prettierrc.js
  packages/@magic-ext/hedera/CHANGELOG.md
  packages/@magic-ext/hedera/LICENSE
  packages/@magic-ext/hedera/package.json
  packages/@magic-ext/hedera/src/index.cdn.ts
  packages/@magic-ext/hedera/src/index.native.ts
  packages/@magic-ext/hedera/src/index.ts
  packages/@magic-ext/hedera/src/types.ts
  packages/@magic-ext/hedera/src/utils.ts
  packages/@magic-ext/hedera/tsconfig.json
  yarn.lock
Labels: major

#601 [minor] Improve dev.ts script for watch & rebuild dependencies
  scripts/bin/dev.ts
Labels: skip-release

#596 Jerryliu sc 81984 update loginwithemailotp interface with new
  packages/@magic-ext/auth/src/index.ts
  packages/@magic-sdk/provider/src/modules/auth.ts
  packages/@magic-sdk/types/src/modules/auth-types.ts
  packages/@magic-sdk/types/src/modules/intermediary-types.ts
Labels: minor

#605 no need to check for sdk platform here.
  packages/@magic-ext/auth/src/index.ts
Labels: minor

#606 Jayhwang type issues
  packages/@magic-sdk/provider/src/modules/nft.ts
  packages/@magic-sdk/types/src/core/json-rpc-types.ts
Labels: patch

#608 Update CHANGELOG.md
  CHANGELOG.md
  yarn.lock
Labels: skip-release

#599 Josh sc 75022 standalone update email v2
  packages/@magic-sdk/provider/test/spec/modules/user/showSettings.spec.ts
  packages/@magic-sdk/types/src/core/deep-link-pages.ts
Labels: minor

#612 Jayhwang sc 85078 update response type for nft purchase
  packages/@magic-sdk/provider/src/modules/nft.ts
  packages/@magic-sdk/types/src/core/json-rpc-types.ts
  packages/@magic-sdk/types/src/index.ts
  packages/@magic-sdk/types/src/modules/nft-types.ts
  yarn.lock
Labels: patch
