Repository magiclabs/magic-js, pull requests merged in 2023-09, with the labels that each got.

#618 import extension from @magic-sdk/commons instead of magick-sdk
  packages/@magic-ext/oauth/package.json
  packages/@magic-ext/oauth/src/index.ts
  yarn.lock
Labels: patch

#598 Jerryliu sc 83009 deprecate updatephonenumber in sdk
  packages/@magic-ext/auth/src/index.ts
  packages/@magic-sdk/provider/src/modules/auth.ts
  packages/@magic-sdk/provider/src/modules/user.ts
  packages/@magic-sdk/provider/test/spec/modules/auth/updatePhoneNumberWithUI.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/user/updatePhoneNumber.spec.ts
  packages/@magic-sdk/types/src/core/json-rpc-types.ts
  yarn.lock
Labels: major

#625 Jayhwang sc 86422 implement magic wallet sendgaslesstxn 2
  packages/@magic-sdk/provider/src/modules/wallet.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/sendGaslessTransaction.spec.ts
  yarn.lock
Labels: patch

#627 Update @magic-ext/oauth crypto-js es module dependency
  packages/@magic-ext/oauth/package.json
  packages/@magic-ext/oauth/src/crypto.ts
  yarn.lock
Labels: patch

#629 Removes Deprecation Warnings for`@magic-ext/auth` methods
  packages/@magic-sdk/provider/src/modules/auth.ts
Labels: patch

#630 adds cdnGlobalName to flow package.json
  packages/@magic-ext/flow/package.json
  yarn.lock
Labels: patch

#638 Jayhwang sc 87905 gas subsidy change sendgaslesstransaction
  packages/@magic-sdk/provider/src/modules/wallet.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/sendGaslessTransaction.spec.ts
  packages/@magic-sdk/types/src/modules/wallet-types.ts
Labels: patch

#636 improve generateKey logic
  packages/@magic-sdk/provider/src/util/web-crypto.ts
  yarn.lock
Labels: minor
