Repository magiclabs/magic-js, pull requests merged in 2023-05, with the labels that each got.

#507 React Native Bare SDK WebView Url Tap Navigate to Device Browser when `open_in_device_browser` is True
  packages/@magic-sdk/react-native-bare/src/react-native-webview-controller.tsx
  yarn.lock
Labels: minor

#509 Update Yarn.lock
  yarn.lock
Labels: minor

#510 update Webview version in README
  packages/@magic-sdk/react-native-expo/README.md
  yarn.lock
Labels: skip-release

#511 [FIX]: updates for Sardines new API spec
  packages/@magic-sdk/types/src/core/json-rpc-types.ts
Labels: patch

#518 Add conditional for `useInstead` of `loginWithMagicLink` `createDeprecationWarning` call
  packages/@magic-sdk/provider/src/modules/auth.ts
Labels: patch

#512 Update getMetdata Type
  packages/@magic-sdk/types/src/modules/user-types.ts
  yarn.lock
Labels: patch

#520 Add symmetric encryption api
  packages/@magic-sdk/provider/src/modules/user.ts
  packages/@magic-sdk/provider/test/spec/modules/user/gdkms.spec.ts
  packages/@magic-sdk/types/src/core/json-rpc-types.ts
  yarn.lock
Labels: minor

#523 Add recovery to DeepLink page
  packages/@magic-sdk/types/src/core/deep-link-pages.ts
  yarn.lock
Labels: patch

#524 Refactor aptos config
  packages/@magic-ext/aptos/src/index.ts
  packages/@magic-ext/aptos/src/type.ts
  yarn.lock
Labels: minor

#529 Implement MagicAptosWallet
  packages/@magic-ext/aptos/package.json
  packages/@magic-ext/aptos/src/MagicAptosWallet.ts
  packages/@magic-ext/aptos/src/constants/index.ts
  packages/@magic-ext/aptos/src/index.ts
  packages/@magic-ext/aptos/src/type.ts
  yarn.lock
Labels: minor
