Repository magiclabs/magic-js, pull requests merged in 2023-07, with the labels that each got.

#562 remove ClearKeys()
  packages/@magic-sdk/provider/src/modules/user.ts
  packages/@magic-sdk/provider/src/modules/wallet.ts
  yarn.lock
Labels: minor

#565 Emit id token on connect - update yarn.lock
  packages/@magic-sdk/provider/README.md
  packages/@magic-sdk/types/README.md
  yarn.lock
Labels: patch

#566 Changelog Update to RN-OAuth ext for testing
  packages/@magic-ext/react-native-bare-oauth/CHANGELOG.md
  yarn.lock
Labels: patch

#567 Reverse Previous Merge Commit
  packages/@magic-ext/react-native-bare-oauth/CHANGELOG.md
Labels: patch

#570 Adds merge_group to Test Workflow
  .github/workflows/test.yml
Labels: skip-release

#572 Adds merge_group to Canary Workflow
  .github/workflows/canary.yml
Labels: skip-release

#568 Minor change to test merge queuing
  packages/@magic-ext/react-native-expo-oauth/CHANGELOG.md
Labels: patch

#569 Minor change to test merge queuing
  packages/@magic-ext/react-native-bare-oauth/CHANGELOG.md
Labels: patch

#573 Fix RN-Expo-OAuth Version History + Revert Change
  packages/@magic-ext/react-native-expo-oauth/CHANGELOG.md
  packages/@magic-ext/react-native-expo-oauth/package.json
Labels: patch

#574 Fix Version History of RN OAuth Packages
  packages/@magic-ext/react-native-bare-oauth/CHANGELOG.md
  packages/@magic-ext/react-native-bare-oauth/package.json
  packages/@magic-ext/react-native-expo-oauth/CHANGELOG.md
  packages/@magic-ext/react-native-expo-oauth/package.json
Labels: patch

#576 Update RN OAuth Packages to correct Version
  packages/@magic-ext/react-native-bare-oauth/package.json
  packages/@magic-ext/react-native-expo-oauth/package.json
Labels: patch

#578 Fix RN Verison packages
  packages/@magic-ext/react-native-bare-oauth/package.json
  packages/@magic-ext/react-native-expo-oauth/package.json
Labels: patch

#579 Fix RN Verison packages
  packages/@magic-ext/react-native-bare-oauth/package.json
  packages/@magic-ext/react-native-expo-oauth/package.json
Labels: patch

#577 Minor update to Changelog to test Deployment Settings
  packages/@magic-ext/bitcoin/CHANGELOG.md
Labels: patch

#580 Minor update to test GH Settings
  packages/@magic-ext/solana/CHANGELOG.md
Labels: patch

#581 Update flow dependencies
  packages/@magic-ext/flow/package.json
  yarn.lock
Labels: minor

#587 Enables WebView Inspection for RN SDKs
  .github/workflows/canary.yml
  .github/workflows/publish.yml
  packages/@magic-sdk/react-native-bare/package.json
  packages/@magic-sdk/react-native-bare/src/react-native-webview-controller.tsx
  packages/@magic-sdk/react-native-expo/package.json
  packages/@magic-sdk/react-native-expo/src/react-native-webview-controller.tsx
  yarn.lock
Labels: patch

#586 Add optional nftEndpoint param
  packages/@magic-ext/auth/src/index.ts
  packages/@magic-sdk/provider/src/core/sdk-environment.ts
  packages/@magic-sdk/provider/src/core/sdk.ts
  packages/@magic-sdk/provider/test/constants.ts
  packages/@magic-sdk/provider/test/factories.ts
  packages/@magic-sdk/provider/test/spec/core/sdk/constructor.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/user/getInfo.spec.ts
  packages/@magic-sdk/react-native-bare/src/index.ts
  packages/@magic-sdk/react-native-expo/src/index.ts
  packages/@magic-sdk/types/src/core/query-types.ts
  packages/magic-sdk/src/index.cdn.ts
  packages/magic-sdk/src/index.ts
Labels: minor

#593 Fix Publish GHA Workflow
  .github/workflows/publish.yml
  packages/@magic-sdk/react-native-bare/README.md
  packages/@magic-sdk/react-native-bare/package.json
  packages/@magic-sdk/react-native-expo/README.md
  packages/@magic-sdk/react-native-expo/package.json
Labels: patch

#595 Remove React-native entry from @magic-ext/auth Package.json
  packages/@magic-ext/auth/package.json
  scripts/bin/wsrun/build-package.ts
  scripts/utils/esbuild.ts
  yarn.lock
Labels: patch
