Repository magiclabs/magic-js, pull requests merged in 2023-06, with the labels that each got.

#531 Change MagicAptosWallet design and fix type mismatch issue
  packages/@magic-ext/aptos/src/MagicAptosWallet.ts
  packages/@magic-ext/aptos/src/index.ts
  packages/@magic-ext/aptos/src/type.ts
Labels: minor

#533 Add test suites for Aptos and fix minor bugs
  packages/@magic-ext/aptos/.eslintrc.js
  packages/@magic-ext/aptos/babel.config.json
  packages/@magic-ext/aptos/jest.config.ts
  packages/@magic-ext/aptos/src/MagicAptosWallet.ts
  packages/@magic-ext/aptos/src/index.ts
  packages/@magic-ext/aptos/test/setup.ts
  packages/@magic-ext/aptos/test/spec/aptos-extension.spec.ts
  packages/@magic-ext/aptos/test/spec/magic-aptos-wallet.spec.ts
  packages/@magic-ext/aptos/test/tsconfig.json
Labels: patch

#534 Minor changes for aptos testing
  packages/@magic-ext/aptos/test/spec/aptos-extension.spec.ts
Labels: skip-release

#536 Replace magic-sdk to @magic-sdk/provider for rn support
  packages/@magic-ext/aptos/package.json
  packages/@magic-ext/aptos/src/MagicAptosWallet.ts
  packages/@magic-ext/aptos/src/index.native.ts
  yarn.lock
Labels: minor

#540 Minor changes for AptosExtension
  packages/@magic-ext/aptos/src/constants/index.ts
  packages/@magic-ext/aptos/src/index.ts
  packages/@magic-ext/aptos/test/spec/aptos-extension.spec.ts
  packages/@magic-ext/aptos/test/spec/magic-aptos-wallet.spec.ts
Labels: patch

#539 [FEAT]: adding types for nft checkout
  packages/@magic-sdk/provider/src/modules/nft.ts
  packages/@magic-sdk/provider/test/spec/modules/nft/purchase.spec.ts
  packages/@magic-sdk/types/src/core/json-rpc-types.ts
Labels: minor

#516 Removes Magic link Method
  packages/@magic-ext/auth/src/index.ts
  packages/@magic-ext/auth/src/util/version-check.ts
  packages/@magic-sdk/provider/src/modules/auth.ts
  packages/@magic-sdk/provider/src/util/version-check.ts
  packages/@magic-sdk/react-native-bare/README.md
  packages/@magic-sdk/react-native-expo/README.md
  yarn.lock
Labels: major

#545 Update RN Expo Package README and Peer dependency
  packages/@magic-sdk/react-native-expo/README.md
  packages/@magic-sdk/react-native-expo/package.json
  yarn.lock
Labels: patch

#552 Fix CI Tests
  jest.config.ts
  packages/@magic-ext/auth/src/index.ts
  packages/@magic-ext/auth/src/util/version-check.ts
  packages/@magic-sdk/provider/src/util/index.ts
  packages/@magic-sdk/provider/test/spec/util/isMajorVersionAtLeast.spec.ts
  yarn.lock
Labels: patch

#555 Fix typo for gdkms
  packages/@magic-ext/gdkms/src/index.ts
  packages/@magic-ext/gdkms/test/spec/gdkms.spec.ts
Labels: patch

#556 Fix Failing CI
  packages/@magic-sdk/provider/test/spec/modules/auth/loginWithMagicLink.spec.ts
Labels: patch

#548 Implement view-in-wallet
  packages/@magic-sdk/provider/src/modules/nft.ts
  packages/@magic-sdk/provider/test/spec/modules/nft/checkout.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/nft/purchase.spec.ts
  packages/@magic-sdk/types/src/core/json-rpc-types.ts
Labels: minor

#549 Remove approval step for canary releases [sc-80045]
  .github/workflows/canary.yml
Labels: patch

#517 Add typings to package.json export
  packages/@magic-ext/aptos/package.json
  packages/@magic-sdk/commons/package.json
  packages/@magic-sdk/provider/package.json
  packages/@magic-sdk/types/package.json
  packages/magic-sdk/package.json
Labels: patch

#551 Updates License to Apache 2.0
  packages/@magic-ext/algorand/LICENSE
  packages/@magic-ext/algorand/package.json
  packages/@magic-ext/auth/LICENSE
  packages/@magic-ext/avalanche/LICENSE
  packages/@magic-ext/bitcoin/LICENSE
  packages/@magic-ext/conflux/LICENSE
  packages/@magic-ext/cosmos/LICENSE
  packages/@magic-ext/ed25519/LICENSE
  packages/@magic-ext/flow/LICENSE
  packages/@magic-ext/harmony/LICENSE
  packages/@magic-ext/icon/LICENSE
  packages/@magic-ext/near/LICENSE
  packages/@magic-ext/oauth/LICENSE
  packages/@magic-ext/oidc/LICENSE
  packages/@magic-ext/polkadot/LICENSE
  packages/@magic-ext/react-native-bare-oauth/LICENSE
  packages/@magic-ext/react-native-bare-oauth/README.md
  packages/@magic-ext/react-native-expo-oauth/LICENSE
  packages/@magic-ext/react-native-expo-oauth/README.md
  packages/@magic-ext/solana/LICENSE
  packages/@magic-ext/taquito/LICENSE
  packages/@magic-ext/terra/LICENSE
  packages/@magic-ext/tezos/LICENSE
  packages/@magic-ext/webauthn/LICENSE
  packages/@magic-ext/zilliqa/LICENSE
  packages/@magic-sdk/commons/README.md
  packages/@magic-sdk/pnp/README.md
  packages/@magic-sdk/provider/README.md
  packages/@magic-sdk/react-native-bare/README.md
  packages/@magic-sdk/react-native-expo/README.md
  packages/@magic-sdk/types/README.md
  packages/magic-sdk/README.md
Labels: minor

#550 Replace `magic-sdk` w/ `@magic-sdk/commons` for `@magic-ext/oidc` Package
  packages/@magic-ext/oidc/package.json
  packages/@magic-ext/oidc/src/index.ts
  yarn.lock
Labels: patch

#560 Revert nft.checkout
  packages/@magic-sdk/provider/src/modules/nft.ts
  yarn.lock
Labels: patch
