Repository magiclabs/magic-js, pull requests merged in 2023-01, with the labels that each got.

#409 add github actions for testing and publishing packages
  .circleci/config.yml
  .github/workflows/publish.yml
  .github/workflows/test.yml
  packages/@magic-ext/algorand/src/index.ts
  yarn.lock
Labels: skip-release

#349 add oidc support
  packages/@magic-ext/oidc/.eslintignore
  packages/@magic-ext/oidc/.eslintrc.js
  packages/@magic-ext/oidc/.lintstagedrc.yml
  packages/@magic-ext/oidc/.prettierrc.js
  packages/@magic-ext/oidc/CHANGELOG.md
  packages/@magic-ext/oidc/LICENSE
  packages/@magic-ext/oidc/README.md
  packages/@magic-ext/oidc/package.json
  packages/@magic-ext/oidc/src/index.cdn.ts
  packages/@magic-ext/oidc/src/index.ts
  packages/@magic-ext/oidc/src/types.ts
  packages/@magic-ext/oidc/tsconfig.json
  yarn.lock
Labels: patch

#416 [CHORE] Add gh_token env var to auto version step
  .github/workflows/publish.yml
Labels: patch

#419 Fix ESLint Issues
  package.json
  packages/@magic-ext/oauth/src/index.ts
  packages/@magic-ext/react-native-oauth/src/index.ts
  packages/@magic-sdk/react-native/src/react-native-webview-controller.tsx
  yarn.lock
Labels: patch

#424 [CHORE] Resolve shipit release issue
  .github/workflows/publish.yml
Labels: skip-release

#425 [CHORE ]add install step in publish stage.
  .github/workflows/publish.yml
Labels: patch

#426 [CHORE] extract build output files to packages directory
  .github/workflows/publish.yml
  yarn.lock
Labels: patch

#427 Update Commons/Provider/Types Packages + Workflow
  .github/workflows/publish.yml
  packages/@magic-sdk/commons/README.md
  packages/@magic-sdk/provider/README.md
  packages/@magic-sdk/types/README.md
Labels: major

#429 [CHORE] Clean up magic-js Deployment Stages
  .github/workflows/publish.yml
  .github/workflows/test.yml
  yarn.lock
Labels: skip-release

#432 Adds react-native-inappbrowser-reborn as peer to Bare RN OAuth
  packages/@magic-ext/react-native-bare-oauth/package.json
  packages/@magic-sdk/react-native-bare/README.md
  packages/@magic-sdk/react-native-expo/README.md
  yarn.lock
Labels: patch, documentation

#431 Replaces WebView View wrapper with SafeAreaView
  packages/@magic-sdk/react-native-bare/README.md
  packages/@magic-sdk/react-native-bare/package.json
  packages/@magic-sdk/react-native-bare/src/react-native-webview-controller.tsx
  packages/@magic-sdk/react-native-bare/test/mocks.ts
  packages/@magic-sdk/react-native-expo/README.md
  packages/@magic-sdk/react-native-expo/package.json
  packages/@magic-sdk/react-native-expo/src/react-native-webview-controller.tsx
  packages/@magic-sdk/react-native-expo/test/mocks.ts
  yarn.lock
Labels: major

#433 Permit React Native entry to Magic Connect Extension
  packages/@magic-ext/connect/README.md
  packages/@magic-ext/connect/package.json
  packages/@magic-ext/connect/src/index.ts
  yarn.lock
Labels: ✨Feature Request, minor

#438 Bump Version of `@magic-sdk/connect` to 6.2.0
  packages/@magic-ext/connect/README.md
Labels: minor

#436 Prevents Relayer from Overriding Status Bar Color
  packages/@magic-sdk/react-native-bare/package.json
  packages/@magic-sdk/react-native-bare/src/react-native-webview-controller.tsx
  packages/@magic-sdk/react-native-expo/package.json
  packages/@magic-sdk/react-native-expo/src/react-native-webview-controller.tsx
  yarn.lock
Labels: patch

#440 Bumps `react-native-webview` peer dependency Requirement to `>=11.0.0`
  packages/@magic-sdk/react-native-bare/package.json
  packages/@magic-sdk/react-native-expo/package.json
  yarn.lock
Labels: skip-release

#441 Bump Version of @magic-sdk/connect to 6.2.0, Again
  packages/@magic-ext/connect/README.md
  packages/@magic-sdk/react-native-bare/README.md
  packages/@magic-sdk/react-native-expo/README.md
Labels: minor
