Repository magiclabs/magic-js, pull requests merged in 2023-10, with the labels that each got.

#639 Add expire email OTP to LoginWithEmailOTPEventOnReceived type
  packages/@magic-sdk/types/src/modules/auth-types.ts
  yarn.lock
Labels: patch

#641 Fix crypto-js type
  packages/@magic-ext/oauth/package.json
  packages/@magic-ext/oauth/src/crypto.ts
  yarn.lock
Labels: patch

#644 Removes React Native entrypoint from all extension's package.json
  BUILD_SYSTEM.md
  packages/@magic-ext/algorand/package.json
  packages/@magic-ext/avalanche/package.json
  packages/@magic-ext/conflux/package.json
  packages/@magic-ext/cosmos/package.json
  packages/@magic-ext/ed25519/package.json
  packages/@magic-ext/flow/package.json
  packages/@magic-ext/hedera/package.json
  packages/@magic-ext/icon/package.json
  packages/@magic-ext/near/package.json
  packages/@magic-ext/polkadot/package.json
  packages/@magic-ext/solana/package.json
  packages/@magic-ext/taquito/package.json
  packages/@magic-ext/terra/package.json
  packages/@magic-ext/tezos/package.json
  packages/@magic-ext/webauthn/package.json
  packages/@magic-ext/zilliqa/package.json
  yarn.lock
Labels: patch

#634 Have the constructor preload iframe assets by default, with optional SDK flag to defer preloading
  packages/@magic-sdk/provider/src/core/sdk.ts
  packages/@magic-sdk/provider/test/spec/core/sdk/overlay.spec.ts
Labels: major

#643 Adds template name to loginWithOTP and loginWithMagicLink
  packages/@magic-sdk/provider/src/modules/auth.ts
  packages/@magic-sdk/provider/test/spec/modules/auth/loginWithEmailOTP.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/auth/loginWithMagicLink.spec.ts
  packages/@magic-sdk/types/src/modules/auth-types.ts
  yarn.lock
Labels: minor

#649 Change NFTCheckoutRequest type
  packages/@magic-sdk/types/src/modules/nft-types.ts
  yarn.lock
Labels: 🐛 Bug Report

#652 Add support for versioned transaction in Solana
  packages/@magic-ext/solana/package.json
  packages/@magic-ext/solana/src/index.ts
  yarn.lock
Labels: minor

#646 allow sepolia for network key
  packages/@magic-sdk/types/src/modules/rpc-provider-types.ts
Labels: patch
