Repository magiclabs/magic-js, pull requests merged in 2023-03, with the labels that each got.

#466 flow getAccount and pass cadence in
  packages/@magic-ext/flow/src/index.ts
  packages/@magic-ext/flow/src/type.ts
  yarn.lock
Labels: minor

#477 Sc 68969 immutable stark error
  packages/@magic-sdk/provider/src/core/sdk-exceptions.ts
  packages/@magic-sdk/provider/test/spec/core/sdk-exceptions/magic-rpc-error/constructor.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/base-module/request.spec.ts
  packages/@magic-sdk/types/src/core/json-rpc-types.ts
  yarn.lock
Labels: patch

#455 feat: [sc-71135] Add purchase SDK method
  packages/@magic-sdk/provider/src/core/sdk.ts
  packages/@magic-sdk/provider/src/modules/nft.ts
  packages/@magic-sdk/provider/test/spec/modules/nft/purchase.spec.ts
  packages/@magic-sdk/types/src/core/json-rpc-types.ts
  yarn.lock
Labels: patch

#479 `@react-native-community/async-storage` => `@react-native-async-storage/async-storage` in RN Bare Package
  packages/@magic-sdk/react-native-bare/package.json
  yarn.lock
Labels: patch

#480 Revert "move third party wallet connections to sdk (#473)"
  jest.config.ts
  package.json
  packages/@magic-sdk/provider/package.json
  packages/@magic-sdk/provider/src/core/sdk-environment.ts
  packages/@magic-sdk/provider/src/core/sdk.ts
  packages/@magic-sdk/provider/src/modules/wallet.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/autoConnectIfWalletBrowser.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/connectToCoinbaseWallet.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/connectToMetaMask.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/connectToThirdPartyWallet-coinbase.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/connectToThirdPartyWallet-metamask.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/connectToThirdPartyWallet-wallet-connect.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/connectToWalletConnect.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/connectWithUI-errors.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/connectWithUI.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/disconnect-wallet-connect.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/disconnect.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/getCoinbaseProvider-config-error.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/getCoinbaseProvider.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/getInfo.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/getMetaMaskProvider.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/getProvider-coinbase-error.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/getProvider-coinbase.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/getProvider-metamask.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/getProvider-wallet-connect-error.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/getProvider-wallet-connect.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/getProvider.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/getUserEnv.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/getWalletConnectProvider-error.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/getWalletConnectProvider.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/handleWalletSelected.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/isCoinbaseWalletBrowser.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/isCoinbaseWalletInstalled.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/isMetaMaskBrowser.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/isMetaMaskInstalled.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/isMobile.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/isWalletEnabled.spec.ts
  packages/@magic-sdk/types/src/core/json-rpc-types.ts
  packages/@magic-sdk/types/src/core/third-party-wallet-options.ts
  packages/@magic-sdk/types/src/index.ts
  scripts/utils/esbuild.ts
  yarn.lock
Labels: major

#487 Jerryliu sc 74424 email otp login invalid email otp event
  packages/@magic-sdk/provider/src/modules/auth.ts
  packages/@magic-sdk/provider/test/spec/modules/auth/loginWithEmailOTPWhitelabel.spec.ts
  packages/@magic-sdk/types/src/modules/auth-types.ts
  yarn.lock
Labels: major

#488 manually update types version in provider package
  packages/@magic-sdk/provider/package.json
  yarn.lock
Labels: patch
