Repository magiclabs/magic-js, pull requests merged in 2023-11, with the labels that each got.

#660 Jayhwang sc 90219 signature verification error solana nova
  packages/@magic-ext/solana/src/index.ts
  yarn.lock
Labels: patch

#661 Adds optional backgroundColor prop to Relayer component
  packages/@magic-sdk/react-native-bare/README.md
  packages/@magic-sdk/react-native-bare/src/react-native-webview-controller.tsx
  packages/@magic-sdk/react-native-expo/src/react-native-webview-controller.tsx
Labels: patch

#662 Add types to sign methods to avoid returning 'any' type
  packages/@magic-ext/solana/src/constants.ts
  packages/@magic-ext/solana/src/index.ts
  packages/@magic-ext/solana/src/type.ts
  yarn.lock
Labels: skip-release

#663 Rename loginWithPopup to loginWithRedirect to match web sdk
  packages/@magic-ext/react-native-bare-oauth/src/index.ts
  packages/@magic-ext/react-native-expo-oauth/src/index.ts
Labels: major

#635 Injectable webcrypto jwt for session persistence
  packages/@magic-sdk/provider/src/core/view-controller.ts
  packages/@magic-sdk/provider/test/spec/core/view-controller/post.spec.ts
Labels: patch

#665 Add `useInternetConnection` hook to track internet connectivity changes
  packages/@magic-sdk/provider/src/core/sdk.ts
  packages/@magic-sdk/provider/src/core/view-controller.ts
  packages/@magic-sdk/provider/test/spec/core/view-controller/post.spec.ts
  packages/@magic-sdk/react-native-bare/README.md
  packages/@magic-sdk/react-native-bare/jest.config.ts
  packages/@magic-sdk/react-native-bare/package.json
  packages/@magic-sdk/react-native-bare/src/hooks.ts
  packages/@magic-sdk/react-native-bare/src/index.ts
  packages/@magic-sdk/react-native-bare/test/mocks.ts
  packages/@magic-sdk/react-native-bare/test/spec/hooks.spec.ts
  packages/@magic-sdk/react-native-expo/README.md
  packages/@magic-sdk/react-native-expo/jest.config.ts
  packages/@magic-sdk/react-native-expo/package.json
  packages/@magic-sdk/react-native-expo/src/hooks.ts
  packages/@magic-sdk/react-native-expo/src/index.ts
  packages/@magic-sdk/react-native-expo/test/mocks.ts
  packages/@magic-sdk/react-native-expo/test/spec/hooks.spec.ts
  yarn.lock
Labels: minor

#668 Revert "Rename: ready -> checkIsReadyForRequest and isReady -> isReadyForRequest"
  packages/@magic-ext/react-native-bare-oauth/src/index.ts
  packages/@magic-ext/react-native-expo-oauth/src/index.ts
  yarn.lock
Labels: major

#670 Fix TypeScript resolution for @magic-ext/* packages when using modern module resolution (node16 etc)
  packages/@magic-ext/algorand/package.json
  packages/@magic-ext/auth/package.json
  packages/@magic-ext/avalanche/package.json
  packages/@magic-ext/bitcoin/package.json
  packages/@magic-ext/conflux/package.json
  packages/@magic-ext/cosmos/package.json
  packages/@magic-ext/ed25519/package.json
  packages/@magic-ext/flow/package.json
  packages/@magic-ext/gdkms/package.json
  packages/@magic-ext/harmony/package.json
  packages/@magic-ext/hedera/package.json
  packages/@magic-ext/icon/package.json
  packages/@magic-ext/near/package.json
  packages/@magic-ext/oauth/package.json
  packages/@magic-ext/oidc/package.json
  packages/@magic-ext/polkadot/package.json
  packages/@magic-ext/react-native-bare-oauth/package.json
  packages/@magic-ext/react-native-expo-oauth/package.json
  packages/@magic-ext/taquito/package.json
  packages/@magic-ext/terra/package.json
  packages/@magic-ext/tezos/package.json
  packages/@magic-ext/webauthn/package.json
  packages/@magic-ext/zilliqa/package.json
Labels: patch

#671 add types to scaffolding export
  scripts/bin/scaffold/template/hybrid/package.json
  scripts/bin/scaffold/template/react-native/package.json
  scripts/bin/scaffold/template/web/package.json
  yarn.lock
Labels: skip-release

#673 Fix: Allow implementers of `view-controller` to set if it's connected to the internet, and reject requests when `isConnectedToInternet` is `false`
  packages/@magic-sdk/provider/src/core/view-controller.ts
  packages/@magic-sdk/provider/test/spec/core/view-controller/post.spec.ts
  packages/@magic-sdk/react-native-bare/package.json
  packages/@magic-sdk/react-native-bare/src/react-native-webview-controller.tsx
  packages/@magic-sdk/react-native-expo/package.json
  packages/@magic-sdk/react-native-expo/src/react-native-webview-controller.tsx
Labels: patch
