Repository magiclabs/magic-js, pull requests merged in 2023-04, with the labels that each got.

#489 Calling magic flow authorization throws error [sc-74792]
  packages/@magic-ext/flow/src/index.ts
  yarn.lock
Labels: patch

#490 Adds `MAGIC_MG_BOX_SEND_RECEIPT` to `MagicIncomingWindowMessage`
  packages/@magic-sdk/types/src/core/message-types.ts
Labels: minor

#493 Remove magic-connect extension
  packages/@magic-ext/connect/.eslintignore
  packages/@magic-ext/connect/.eslintrc.js
  packages/@magic-ext/connect/.lintstagedrc.yml
  packages/@magic-ext/connect/.prettierrc.js
  packages/@magic-ext/connect/CHANGELOG.md
  packages/@magic-ext/connect/LICENSE
  packages/@magic-ext/connect/README.md
  packages/@magic-ext/connect/package.json
  packages/@magic-ext/connect/src/index.cdn.ts
  packages/@magic-ext/connect/src/index.ts
  packages/@magic-ext/connect/src/types.ts
  packages/@magic-ext/connect/tsconfig.json
  yarn.lock
Labels: skip-release

#491 Remove Beta Warning from RN packages
  packages/@magic-sdk/react-native-bare/README.md
  packages/@magic-sdk/react-native-expo/README.md
Labels: minor

#492 Jerryliu sc 74225 custom auth extension in magic js
  packages/@magic-sdk/provider/src/modules/auth.ts
  packages/@magic-sdk/types/src/core/json-rpc-types.ts
  yarn.lock
Labels: minor

#498 Jerryliu sc 75641 lazer request showsettings page mfa
  packages/@magic-sdk/provider/src/modules/user.ts
  packages/@magic-sdk/provider/test/spec/modules/user/showSettings.spec.ts
  packages/@magic-sdk/types/src/core/deep-link-pages.ts
  packages/@magic-sdk/types/src/modules/user-types.ts
  yarn.lock
Labels: minor

#499 hotfix export types to index.ts
  packages/@magic-sdk/types/src/index.ts
  yarn.lock
Labels: patch

#502 quick fix passing authorization token in payload
  packages/@magic-ext/auth/src/index.ts
  packages/@magic-sdk/provider/src/modules/auth.ts
  yarn.lock
Labels: patch
