Repository magiclabs/magic-js, pull requests merged in 2023-02, with the labels that each got.

#446 move connect methods to wallet module under magic-sdk
  packages/@magic-sdk/provider/src/core/sdk.ts
  packages/@magic-sdk/provider/src/modules/wallet.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/connectWithUI.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/disconnect.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/getInfo.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/requestUserInfoWithUI.spec.ts
  packages/@magic-sdk/provider/test/spec/modules/wallet/showUI.spec.ts
  packages/@magic-sdk/types/src/core/json-rpc-types.ts
  yarn.lock
Labels: minor

#451 Permit React Native SDK to Utlize Bitcoin extension
  packages/@magic-ext/bitcoin/package.json
  yarn.lock
Labels: patch

#453 Updates PR Template warning about one label
  .github/PULL_REQUEST_TEMPLATE.md
Labels: skip-release

#454 Update Package versions
  packages/@magic-sdk/provider/README.md
  packages/@magic-sdk/types/README.md
Labels: minor

#457 Udpates `expo-web-browser` to the latest for `@magic-ext/react-native-expo-oauth`
  packages/@magic-ext/react-native-expo-oauth/package.json
  yarn.lock
Labels: minor

#458 * Add recoverAccount api
  packages/@magic-sdk/provider/src/modules/user.ts
  packages/@magic-sdk/provider/test/spec/modules/user/recoverAccount.spec.ts
  packages/@magic-sdk/types/src/core/json-rpc-types.ts
  packages/@magic-sdk/types/src/modules/user-types.ts
Labels: minor

#461 * Update yarn.lock
  yarn.lock
Labels: minor
