Repository magiclabs/magic-js, pull requests merged in 2024-11, with the labels that each got.

#832 Pdeexp 1544 implement magic auth recover account provider
  packages/@magic-sdk/provider/src/modules/user.ts
  packages/@magic-sdk/provider/test/spec/modules/user/recoverAccount.spec.ts
  packages/@magic-sdk/types/src/modules/intermediary-types.ts
  packages/@magic-sdk/types/src/modules/user-types.ts
  yarn.lock
Labels: minor

#833 feat: implement transition from recover account to update email flow …
  packages/@magic-sdk/provider/src/modules/user.ts
  packages/@magic-sdk/provider/test/spec/modules/user/recoverAccount.spec.ts
  packages/@magic-sdk/types/src/modules/user-types.ts
Labels: minor

#837 feat: add customData property to OAuthRedirectConfiguration
  packages/@magic-ext/oauth2/src/types.ts
  yarn.lock
Labels: patch

#830 fix: typos
  BUILD_SYSTEM.md
  CONTRIBUTING.md
Labels: skip-release
