Repository magiclabs/magic-js, pull requests merged in 2024-08, with the labels that each got.

#775 Chore/pdeexp 1658 update login sdk method to handle did lifespan
  packages/@magic-ext/oauth/src/index.ts
  packages/@magic-ext/oauth/src/types.ts
  packages/@magic-ext/oauth2/src/types.ts
  packages/@magic-ext/oidc/src/types.ts
  packages/@magic-ext/react-native-bare-oauth/src/index.ts
  packages/@magic-ext/react-native-bare-oauth/src/types.ts
  packages/@magic-ext/react-native-expo-oauth/src/index.ts
  packages/@magic-ext/react-native-expo-oauth/src/types.ts
Labels: minor

#777 Add new types for whitelabel sms
  packages/@magic-sdk/types/src/modules/auth-types.ts
  packages/@magic-sdk/types/src/modules/intermediary-types.ts
Labels: minor

#772 change display css to visibility
  packages/magic-sdk/src/iframe-controller.ts
  packages/magic-sdk/test/spec/iframe-controller/hideOverlay.spec.ts
  packages/magic-sdk/test/spec/iframe-controller/init.spec.ts
  packages/magic-sdk/test/spec/iframe-controller/showOverlay.spec.ts
  yarn.lock
Labels: patch

#780 Revert unexpected master changes
  package.json
  packages/@magic-sdk/provider/test/spec/modules/auth/loginWithEmailOTPWhitelabel.spec.ts
Labels: skip-release

#778 Enable MFA to be standalone flow
  packages/@magic-sdk/provider/src/modules/user.ts
  packages/@magic-sdk/provider/test/spec/modules/user/mfa.spec.ts
  packages/@magic-sdk/types/src/core/json-rpc-types.ts
Labels: minor

#781 feat: added new event for controlling close by user
  packages/@magic-sdk/provider/src/util/promise-tools.ts
  packages/@magic-sdk/types/src/modules/user-types.ts
  yarn.lock
Labels: minor

#768 Enable whitelabel customization for sms login
  packages/@magic-sdk/provider/src/modules/auth.ts
  packages/@magic-sdk/provider/test/spec/modules/auth/loginWithSmsWhitelabel.spec.ts
  packages/@magic-sdk/types/src/modules/intermediary-types.ts
  yarn.lock
Labels: minor
