Repository magiclabs/magic-js, pull requests merged in 2024-02, with the labels that each got.

#703 Add npm provenance
  .github/workflows/canary.yml
  .github/workflows/publish.yml
  .github/workflows/test.yml
  lerna.json
  package.json
  packages/@magic-ext/webauthn/README.md
  packages/@magic-sdk/commons/README.md
  packages/@magic-sdk/pnp/README.md
  packages/@magic-sdk/provider/README.md
  packages/@magic-sdk/react-native-bare/README.md
  packages/@magic-sdk/react-native-expo/README.md
  packages/@magic-sdk/types/README.md
  packages/magic-sdk/README.md
  yarn.lock
Labels: patch

#708 [FEAT]: adding meta field to @magic-sdk magic constructor
  packages/@magic-sdk/provider/src/core/sdk.ts
  packages/@magic-sdk/types/src/core/query-types.ts
  yarn.lock
Labels: minor

#709 updateEmail: Adds event for email already exists
  packages/@magic-sdk/types/src/modules/auth-types.ts
  yarn.lock
Labels: patch

#710 New OAuth 2 ext package
  packages/@magic-ext/oauth2/.eslintignore
  packages/@magic-ext/oauth2/.eslintrc.js
  packages/@magic-ext/oauth2/.lintstagedrc.yml
  packages/@magic-ext/oauth2/.prettierrc.js
  packages/@magic-ext/oauth2/CHANGELOG.md
  packages/@magic-ext/oauth2/LICENSE
  packages/@magic-ext/oauth2/README.md
  packages/@magic-ext/oauth2/package.json
  packages/@magic-ext/oauth2/src/index.cdn.ts
  packages/@magic-ext/oauth2/src/index.ts
  packages/@magic-ext/oauth2/src/types.ts
  packages/@magic-ext/oauth2/tsconfig.json
  yarn.lock
Labels: patch, prerelease

#712 OAuth 2: fix publishing
  package.json
  packages/@magic-ext/oauth2/package.json
  yarn.lock
Labels: major

#714 Fixing publishing related to "auto" bug
  package.json
  packages/@magic-ext/oauth2/package.json
  yarn.lock
Labels: 🔥 Priority 1, major

#718 Add new "Product Announcement" Relayer Message Type
  packages/@magic-sdk/provider/src/core/sdk-exceptions.ts
  packages/@magic-sdk/provider/src/core/view-controller.ts
  packages/@magic-sdk/provider/test/constants.ts
  packages/@magic-sdk/provider/test/spec/core/sdk-exceptions/warning-factories.spec.ts
  packages/@magic-sdk/provider/test/spec/core/view-controller/listen.spec.ts
  packages/@magic-sdk/types/src/core/exception-types.ts
  packages/@magic-sdk/types/src/core/json-rpc-types.ts
  packages/@magic-sdk/types/src/core/message-types.ts
  yarn.lock
Labels: minor

#715 Add ability to use server callback url for start of oauth2 flow
  packages/@magic-ext/oauth2/src/index.ts
  packages/@magic-ext/oauth2/src/types.ts
  yarn.lock
Labels: minor

#719 Update Pull Request Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: skip-release
