Repository magiclabs/magic-js, pull requests merged in 2024-03, with the labels that each got.

#721 Adds Response Time out Error to RN SDKs
  packages/@magic-sdk/provider/src/core/sdk-exceptions.ts
  packages/@magic-sdk/provider/test/spec/core/sdk-exceptions/error-factories.spec.ts
  packages/@magic-sdk/provider/test/spec/core/view-controller/post.spec.ts
  packages/@magic-sdk/react-native-bare/src/react-native-webview-controller.tsx
  packages/@magic-sdk/react-native-bare/test/spec/react-native-webview-controller/_post.spec.ts
  packages/@magic-sdk/react-native-expo/src/react-native-webview-controller.tsx
  packages/@magic-sdk/react-native-expo/test/spec/react-native-webview-controller/_post.spec.ts
  packages/@magic-sdk/types/src/core/exception-types.ts
  yarn.lock
Labels: minor

#724 updates readme
  packages/@magic-ext/oauth2/README.md
  yarn.lock
Labels: patch

#725 Reverts - Adds Response Time out Error to RN SDKs
  packages/@magic-sdk/provider/src/core/sdk-exceptions.ts
  packages/@magic-sdk/provider/test/spec/core/sdk-exceptions/error-factories.spec.ts
  packages/@magic-sdk/provider/test/spec/core/view-controller/post.spec.ts
  packages/@magic-sdk/react-native-bare/src/react-native-webview-controller.tsx
  packages/@magic-sdk/react-native-bare/test/spec/react-native-webview-controller/_post.spec.ts
  packages/@magic-sdk/react-native-expo/src/react-native-webview-controller.tsx
  packages/@magic-sdk/react-native-expo/test/spec/react-native-webview-controller/_post.spec.ts
  packages/@magic-sdk/types/src/core/exception-types.ts
Labels: minor

#726 Update Auto to latest in an attempt to fix versioning error
  package.json
  yarn.lock
Labels: skip-release

#727 Add an option for crypto-checkout
  packages/@magic-sdk/provider/test/spec/modules/nft/checkout.spec.ts
  packages/@magic-sdk/types/src/modules/nft-types.ts
Labels: patch

#699 Add private key reveal method
  packages/@magic-sdk/provider/src/modules/user.ts
  packages/@magic-sdk/provider/test/spec/modules/user/revealPrivateKey.spec.ts
  packages/@magic-sdk/types/src/core/json-rpc-types.ts
  packages/@magic-sdk/types/src/modules/intermediary-types.ts
Labels: minor

#729 Pdeexp 681 fix magic js launching script
  .github/workflows/publish.yml
  packages/@magic-ext/oauth/README.md
  yarn.lock
Labels: patch

#730 revert --dry-run
  .github/workflows/publish.yml
Labels: patch

#731 readme change
  README.md
  yarn.lock
Labels: patch

#732 readme edit
  packages/@magic-sdk/provider/README.md
Labels: patch
